---
title: "Berries_EDA"
author: "Haoyu Li"
date: "10/18/2020"
output: pdf_document
---

```{r setup, include=FALSE}
library(knitr)
library(tidyverse)
library(magrittr)
library(stats)
opts_chunk$set(echo = FALSE)
```

```{r}
#read cleaned data
sberry<-read.csv("strawberry.csv")
sberry%<>%select(-X)
sberry$production%>%unique()
```


```{r}
df_1<-sberry%<>%select(Year,State,production,Chemical,Value)

#filter out the productions that do not exist
df_1%<>%filter(Chemical != "")

#filter out NA and D value
df_1%<>% filter(Value != "(D)")

df_1%<>% filter(Value !=  "(NA)")

df_1%<>%filter(Value != "(Z)")

df_1$Value<-as.numeric(df_1$Value)

```



-Basic data summary
```{r}
#summarize the chemical usage
s1<-df_1%>%group_by(State,Chemical)%>%summarise(total = sum(Value))
view(s1)

#boxplot of Chemical 
ggplot(data = df_1) +
  geom_boxplot(mapping = aes(x = Chemical, y = Value)) +
  theme(axis.title = element_text(size = 13, face = "bold")) +
  labs(x = "Chemical Type")

#count each production by the chemical categories
ggplot(data=df_1)+
  geom_bar(mapping=aes(x=production,fill=Chemical),position = "dodge")+
  theme(axis.title = element_text(size = 13, face = "bold")) +
  labs(x = "Production")


```
-No obvious outliers by just looking at the boxplot


-Then we will do PCA Analysis


```{r}
# prepare data


df_2<-df_1%>%select(State,Chemical,Value)
df_2[is.na(df_2)]<-0
df_3<-df_2%>%group_by(State,Chemical)%>%summarise(total = sum(Value))
df_4 <- df_3%>%pivot_wider(names_from = Chemical,values_from = total)
df_4[is.na(df_4)] <-0
df_5<-df_4[,-1]


# find variable describing the most variance
df_5_var <- apply(df_5, 2, var)
print(df_5_var)
max(df_5_var)
which(df_5_var == max(df_5_var))
min(df_5_var)
which(df_5_var == min(df_5_var))

```
-Correlation matrix
```{r}
cor_m <- cor(df_5)
print(cor_m)

```
-PCA
```{r}
pca <- prcomp(df_5, center = TRUE, scale. = TRUE)
print(pca)
summary(pca)

# flip values to positives
pca_1 <- pca
pca_1$rotation <- -pca_1$rotation
pca_1$x <- -pca_1$x
print(pca_1)
summary(pca_1)

# PCA scatter plot
pc_2 <- data.frame(pca_1$rotation[, 1:2])
pc_2$Chemical <- rownames(pc_2)
plot1 <- ggplot(pc_2, aes(x = PC1, y = PC2))
plot1 <- plot1 + geom_point(size = 2) +
  geom_text(aes(label = Chemical), vjust = 1) +
  theme(axis.text = element_text(size = 10),
        axis.title = element_text(size = 10, face = "bold"))
print(plot1)
```





